Repository depromeet/12-team3-backend, pull requests merged in 2022-12, with the labels that each got.

#21 UserToken 타입
  application/src/main/java/com/depromeet/ahmatda/user/UserController.java
  application/src/main/java/com/depromeet/ahmatda/user/UserControllerAdvice.java
  application/src/main/java/com/depromeet/ahmatda/user/UserRegisterCode.java
  application/src/main/java/com/depromeet/ahmatda/user/constraint/DeviceIdConstraint.java
  application/src/main/java/com/depromeet/ahmatda/user/constraint/DeviceIdValidator.java
  application/src/main/java/com/depromeet/ahmatda/user/dto/SignUpRequestDto.java
  application/src/main/java/com/depromeet/ahmatda/user/exception/UserExistException.java
  application/src/main/java/com/depromeet/ahmatda/user/exception/UserNotExistException.java
  application/src/main/java/com/depromeet/ahmatda/user/service/UserService.java
  application/src/main/java/com/depromeet/ahmatda/user/service/impl/DeviceUserService.java
  application/src/main/java/com/depromeet/ahmatda/user/token/UserToken.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/document/user/UserControllerTest.java
  domain/src/main/java/com/depromeet/ahmatda/domain/emoji/AhmatdaEmoji.java
  domain/src/main/java/com/depromeet/ahmatda/domain/user/User.java
  domain/src/main/java/com/depromeet/ahmatda/domain/user/adaptor/UserAdaptor.java
  domain/src/main/java/com/depromeet/ahmatda/domain/user/repository/UserRepository.java
Labels: please review

#25 온보딩 및 유저 체크
  application/src/docs/asciidoc/common/onboardingCategory.adoc
  application/src/docs/asciidoc/common/userRegisterCode.adoc
  application/src/docs/asciidoc/index.adoc
  application/src/main/java/com/depromeet/ahmatda/category/service/CategoryService.java
  application/src/main/java/com/depromeet/ahmatda/category/service/impl/DeviceCategoryService.java
  application/src/main/java/com/depromeet/ahmatda/onboard/OnboardingRequest.java
  application/src/main/java/com/depromeet/ahmatda/onboard/OnboardingService.java
  application/src/main/java/com/depromeet/ahmatda/template/service/TemplateService.java
  application/src/main/java/com/depromeet/ahmatda/template/service/impl/DeviceTemplateService.java
  application/src/main/java/com/depromeet/ahmatda/user/UserController.java
  application/src/main/java/com/depromeet/ahmatda/user/UserRegisterCode.java
  application/src/main/java/com/depromeet/ahmatda/user/dto/SignUpRequest.java
  application/src/main/java/com/depromeet/ahmatda/user/service/UserService.java
  application/src/main/java/com/depromeet/ahmatda/user/service/impl/DeviceUserService.java
  application/src/main/java/com/depromeet/ahmatda/user/token/UserToken.java
  application/src/main/java/com/depromeet/ahmatda/user/token/UserTokenSerializer.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/document/CommonController.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/document/EnumDocs.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/document/test/CommonDocsTest.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/document/user/UserControllerTest.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/util/DocumentEnumLinkGenerator.java
  domain/src/main/java/com/depromeet/ahmatda/domain/category/adaptor/CategoryAdaptor.java
  domain/src/main/java/com/depromeet/ahmatda/domain/item/Item.java
  domain/src/main/java/com/depromeet/ahmatda/domain/onboard/OnBoardingCategory.java
Labels: please review

#28 CORS mapping to all origin
  application/src/main/java/com/depromeet/ahmatda/config/CorsConfig.java
Labels: enhancement

#29 카테고리 수정시 created_at null, user_id null 로 들어가는 버그 수정
  application/src/main/java/com/depromeet/ahmatda/category/dto/CategoryRequest.java
  domain/src/main/java/com/depromeet/ahmatda/domain/BaseTimeEntity.java
Labels: bug

#31 :fire: Alarm config
  .github/workflows/build.yml
  application/build.gradle
  application/src/main/java/com/depromeet/ahmatda/alarm/FcmController.java
  application/src/main/java/com/depromeet/ahmatda/alarm/FcmMessage.java
  application/src/main/java/com/depromeet/ahmatda/alarm/FcmService.java
  application/src/main/resources/firebase/fcm-account.json
Labels: please review

#32 :fire: Request Logging AOP
  application/src/main/java/com/depromeet/ahmatda/config/LoggingAspect.java
Labels: please review

#33 Config/jacoco
  .github/workflows/build.yml
  build.gradle
  common/src/test/java/com/depromeet/ahmatda/CommonApplicationTests.java
  domain/src/test/java/com/depromeet/ahmatda/DomainApplicationTests.java
  inner-system/src/test/java/com/depromeet/ahmatda/InnerSystemApplicationTests.java
Labels: please review

#34 :fire: renew FCM Token API
  application/src/docs/asciidoc/index.adoc
  application/src/main/java/com/depromeet/ahmatda/user/UserController.java
  application/src/main/java/com/depromeet/ahmatda/user/service/UserService.java
  application/src/main/java/com/depromeet/ahmatda/user/service/impl/DeviceUserService.java
  application/src/main/java/com/depromeet/ahmatda/user/token/FcmToken.java
  application/src/test/java/com/depromeet/ahmatda/application/apidocs/document/user/UserControllerTest.java
  domain/src/main/java/com/depromeet/ahmatda/domain/user/User.java
  domain/src/main/java/com/depromeet/ahmatda/domain/user/adaptor/UserAdaptor.java
Labels: please review
